H1 frost function, BIP034 hashing function
threshold-network/roast-go pull request #2
Opened 2023-12-12 15:32 UTC by pdyraga

Depends on #1. Let's merge #1 before we undraft/merge this one.

This changeset adds H1 function as specified in section 6.5. FROST(secp256k1, SHA-256) of [FROST]. The [BIP340] hash function is used as expand_message_xmd. The implementation is copied from @eth-r's prototype. I added tests and annotated relevant parts of the hash functions code with reference to papers. The `testutils` library code was borrowed from the `keep-network/keep-core` repository.

2023-12-12 16:07 UTC, eth-r requested changes
A couple of errors regarding the comments and the context string. I don't think a BIP-340 actually uses HASH-TO-CURVE specifications for anything because it has its own, simpler hashing rules.

2023-12-12 16:07 UTC, eth-r commented on roast/hash.go
> +	// The hash_to_field function is specified in [HASH-TO-CURVE] in section
We are not actually doing this when implementing BIP-340 which has a much simpler specification for hashing scalars.

2023-12-12 16:07 UTC, eth-r commented on roast/hash.go
> +var contextString = []byte("FROST-secp256k1-SHA256-v1")
Mismatch with comment above

2023-12-12 16:07 UTC, eth-r commented on roast/roast.go
> +//	<https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve-16>.
I think HASH-TO-CURVE is just superseded by the BIP-340 hashing specification.

2023-12-13 09:03 UTC, pdyraga commented on roast/hash.go
> +var contextString = []byte("FROST-secp256k1-SHA256-v1")
Fixed in https://github.com/threshold-network/roast-go/pull/2/commits/7644d8031a9291e45314854d55566cc2402c0a56.

2023-12-13 09:04 UTC, pdyraga commented on roast/hash.go
> +	// The hash_to_field function is specified in [HASH-TO-CURVE] in section
👍🏻 Please see https://github.com/threshold-network/roast-go/pull/2/commits/bac833c55b4a5950897ab2193bb854fc37594bb8.

2023-12-13 09:04 UTC, pdyraga commented on roast/roast.go
> +//	<https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve-16>.
See https://github.com/threshold-network/roast-go/pull/2/commits/bac833c55b4a5950897ab2193bb854fc37594bb8 , please.

2023-12-13 09:11 UTC, pdyraga commented
Note that this specification is specific to BIP340, in the next PR I am planning to abstract out an interface that would allow us to provide another hashing strategy.

2023-12-13 13:12 UTC, eth-r approved these changes

2023-12-13 13:29 UTC, merged